In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [4]:
df=pd.read_csv('Churn_Modelling.csv',index_col='RowNumber')

In [5]:
df.head()

CustomerId   Surname  CreditScore Geography  Gender  Age  Tenure  \
RowNumber                                                                     
1            15634602  Hargrave          619    France  Female   42       2   
2            15647311      Hill          608     Spain  Female   41       1   
3            15619304      Onio          502    France  Female   42       8   
4            15701354      Boni          699    France  Female   39       1   
5            15737888  Mitchell          850     Spain  Female   43       2   

             Balance  NumOfProducts  HasCrCard  IsActiveMember  \
RowNumber                                                        
1               0.00              1          1               1   
2           83807.86              1          0               1   
3          159660.80              3          1               0   
4               0.00              2          0               0   
5          125510.82              1          1               1   

           EstimatedSalary  Exited  
RowNumber                           
1                101348.88       1  
2                112542.58       0  
3                113931.57       1  
4                 93826.63       0  
5                 79084.10       0

In [7]:
df=df.drop(['CustomerId','Surname'],axis=1)

In [8]:
df

CreditScore Geography  Gender  Age  Tenure    Balance  \
RowNumber                                                          
1                  619    France  Female   42       2       0.00   
2                  608     Spain  Female   41       1   83807.86   
3                  502    France  Female   42       8  159660.80   
4                  699    France  Female   39       1       0.00   
5                  850     Spain  Female   43       2  125510.82   
...                ...       ...     ...  ...     ...        ...   
9996               771    France    Male   39       5       0.00   
9997               516    France    Male   35      10   57369.61   
9998               709    France  Female   36       7       0.00   
9999               772   Germany    Male   42       3   75075.31   
10000              792    France  Female   28       4  130142.79   

           NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  
RowNumber                                                                     
1                      1          1               1        101348.88       1  
2                      1          0               1        112542.58       0  
3                      3          1               0        113931.57       1  
4                      2          0               0         93826.63       0  
5                      1          1               1         79084.10       0  
...                  ...        ...             ...              ...     ...  
9996                   2          1               0         96270.64       0  
9997                   1          1               1        101699.77       0  
9998                   1          0               1         42085.58       1  
9999                   2          1               0         92888.52       1  
10000                  1          1               0         38190.78       0  

[10000 rows x 11 columns]

In [18]:
x=df.drop('Exited',axis=1).values

In [20]:
y=df['Exited'].values

In [21]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [22]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [24]:
from sklearn.preprocessing import LabelEncoder
x_transformer=LabelEncoder()

In [25]:
x[:, 1] = x_transformer.fit_transform(x[:, 1])

In [26]:
x[:,2]=x_transformer.fit_transform(x[:,2])

In [29]:
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

transform = ColumnTransformer([("countries", OneHotEncoder(), [1])], remainder="passthrough") # 1 is the country column
x = transform.fit_transform(x)
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

NameError: name 'train_test_split' is not defined

In [31]:
from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [36]:
classifier= Sequential()

In [40]:
#Add input layer and hidden layer
classifier.add(Dense(6, activation = 'relu', input_shape = (x_train.shape[1], )))
classifier.add(Dropout(rate = 0.1))

In [41]:
#Add second layer
classifier.add(Dense(6, activation = 'relu'))
classifier.add(Dropout(rate = 0.1))

In [42]:
classifier.add(Dense(1,activation='sigmoid'))

In [43]:
classifier.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 6)                 78        
                                                                 
 dropout (Dropout)           (None, 6)                 0         
                                                                 
 dense_2 (Dense)             (None, 6)                 42        
                                                                 
 dropout_1 (Dropout)         (None, 6)                 0         
                                                                 
 dense_3 (Dense)             (None, 1)                 7         
                                                                 
Total params: 127 (508.00 Byte)
Trainable params: 127 (508.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [44]:
#Optimize the weights
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [46]:
#Fitting the Neural Network
history = classifier.fit(x_train, y_train, batch_size = 32, epochs = 200, validation_split = 0.1, verbose = 2)

Epoch 1/200
225/225 - 2s - loss: 0.7170 - accuracy: 0.5718 - val_loss: 0.5603 - val_accuracy: 0.7950 - 2s/epoch - 10ms/step
Epoch 2/200
225/225 - 1s - loss: 0.5177 - accuracy: 0.7847 - val_loss: 0.4540 - val_accuracy: 0.8100 - 513ms/epoch - 2ms/step
Epoch 3/200
225/225 - 0s - loss: 0.4834 - accuracy: 0.7904 - val_loss: 0.4350 - val_accuracy: 0.8087 - 483ms/epoch - 2ms/step
Epoch 4/200
225/225 - 1s - loss: 0.4652 - accuracy: 0.7933 - val_loss: 0.4227 - val_accuracy: 0.8112 - 503ms/epoch - 2ms/step
Epoch 5/200
225/225 - 1s - loss: 0.4539 - accuracy: 0.7971 - val_loss: 0.4155 - val_accuracy: 0.8112 - 521ms/epoch - 2ms/step
Epoch 6/200
225/225 - 0s - loss: 0.4503 - accuracy: 0.7972 - val_loss: 0.4110 - val_accuracy: 0.8138 - 498ms/epoch - 2ms/step
Epoch 7/200
225/225 - 0s - loss: 0.4449 - accuracy: 0.8026 - val_loss: 0.4056 - val_accuracy: 0.8163 - 469ms/epoch - 2ms/step
Epoch 8/200
225/225 - 1s - loss: 0.4403 - accuracy: 0.8051 - val_loss: 0.4013 - val_accuracy: 0.8150 - 503ms/epoch - 2ms

Epoch 66/200
225/225 - 0s - loss: 0.3671 - accuracy: 0.8489 - val_loss: 0.3343 - val_accuracy: 0.8575 - 422ms/epoch - 2ms/step
Epoch 67/200
225/225 - 0s - loss: 0.3677 - accuracy: 0.8501 - val_loss: 0.3354 - val_accuracy: 0.8537 - 401ms/epoch - 2ms/step
Epoch 68/200
225/225 - 0s - loss: 0.3700 - accuracy: 0.8475 - val_loss: 0.3371 - val_accuracy: 0.8550 - 430ms/epoch - 2ms/step
Epoch 69/200
225/225 - 0s - loss: 0.3682 - accuracy: 0.8525 - val_loss: 0.3358 - val_accuracy: 0.8562 - 423ms/epoch - 2ms/step
Epoch 70/200
225/225 - 0s - loss: 0.3696 - accuracy: 0.8486 - val_loss: 0.3363 - val_accuracy: 0.8600 - 393ms/epoch - 2ms/step
Epoch 71/200
225/225 - 0s - loss: 0.3694 - accuracy: 0.8507 - val_loss: 0.3351 - val_accuracy: 0.8600 - 448ms/epoch - 2ms/step
Epoch 72/200
225/225 - 0s - loss: 0.3714 - accuracy: 0.8469 - val_loss: 0.3359 - val_accuracy: 0.8562 - 420ms/epoch - 2ms/step
Epoch 73/200
225/225 - 0s - loss: 0.3670 - accuracy: 0.8478 - val_loss: 0.3341 - val_accuracy: 0.8562 - 428ms/e

Epoch 131/200
225/225 - 0s - loss: 0.3698 - accuracy: 0.8468 - val_loss: 0.3346 - val_accuracy: 0.8600 - 439ms/epoch - 2ms/step
Epoch 132/200
225/225 - 0s - loss: 0.3645 - accuracy: 0.8511 - val_loss: 0.3328 - val_accuracy: 0.8612 - 462ms/epoch - 2ms/step
Epoch 133/200
225/225 - 1s - loss: 0.3650 - accuracy: 0.8496 - val_loss: 0.3338 - val_accuracy: 0.8600 - 521ms/epoch - 2ms/step
Epoch 134/200
225/225 - 0s - loss: 0.3646 - accuracy: 0.8501 - val_loss: 0.3336 - val_accuracy: 0.8612 - 424ms/epoch - 2ms/step
Epoch 135/200
225/225 - 0s - loss: 0.3674 - accuracy: 0.8512 - val_loss: 0.3333 - val_accuracy: 0.8600 - 407ms/epoch - 2ms/step
Epoch 136/200
225/225 - 0s - loss: 0.3663 - accuracy: 0.8500 - val_loss: 0.3319 - val_accuracy: 0.8600 - 412ms/epoch - 2ms/step
Epoch 137/200
225/225 - 0s - loss: 0.3673 - accuracy: 0.8478 - val_loss: 0.3326 - val_accuracy: 0.8600 - 419ms/epoch - 2ms/step
Epoch 138/200
225/225 - 0s - loss: 0.3687 - accuracy: 0.8494 - val_loss: 0.3329 - val_accuracy: 0.8612 -

225/225 - 0s - loss: 0.3668 - accuracy: 0.8489 - val_loss: 0.3318 - val_accuracy: 0.8525 - 356ms/epoch - 2ms/step
Epoch 196/200
225/225 - 0s - loss: 0.3582 - accuracy: 0.8551 - val_loss: 0.3313 - val_accuracy: 0.8550 - 351ms/epoch - 2ms/step
Epoch 197/200
225/225 - 0s - loss: 0.3629 - accuracy: 0.8512 - val_loss: 0.3311 - val_accuracy: 0.8537 - 415ms/epoch - 2ms/step
Epoch 198/200
225/225 - 0s - loss: 0.3647 - accuracy: 0.8512 - val_loss: 0.3328 - val_accuracy: 0.8550 - 431ms/epoch - 2ms/step
Epoch 199/200
225/225 - 0s - loss: 0.3699 - accuracy: 0.8483 - val_loss: 0.3331 - val_accuracy: 0.8537 - 467ms/epoch - 2ms/step
Epoch 200/200
225/225 - 0s - loss: 0.3656 - accuracy: 0.8501 - val_loss: 0.3317 - val_accuracy: 0.8550 - 432ms/epoch - 2ms/step


In [49]:
y_pred = classifier.predict(x_test)


63/63 [==============================] - 0s 2ms/step


In [51]:
y_pred = (y_pred > 0.5).astype(int)
print(y_pred[:5])

[[0]
 [0]
 [0]
 [0]
 [0]]


In [52]:
#Making the Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1549   42]
 [ 239  170]]
